version: 2
jobs:
  build:
    filters:
      branches:
        only: develop
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Build
          command: npm run prod
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
